[tool.poetry]
name = "AISExplorer"
version = "0.1.0"
description = "Wrapper to fetch data from marinetraffic.com"
readme = "README.rst"
homepage = "https://github.com/johnfraney/flake8-markdown"
repository = "https://github.com/johnfraney/flake8-markdown"
authors = ["reyemb <reyemb.coding@gmail.com>"]


[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"
pandas = "^1.3.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
jupyter = "^1.0.0"
jupyterlab = "^3.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
